name: CI-Build

on:
  push: 
    branches: [ "develop", "main", "release/*" ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
    
        - name: Setup .NET 7.x
          uses: actions/setup-dotnet@v3
          with: 
            dotnet-version: 7.x
    
        - name: Build and Run Tests
          run: ./build.sh --target=ContinuousIntegrationBuild
          shell: bash
    
        - name: Generate Code Coverage Report
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: /build/artifacts/testResults/coverlet/**/coverage.cobertura.xml
            badge: true
            fail_below_min: true
            format: markdown
            hide_branch_rate: false
            hide_complexity: false
            indicators: true
            output: both
            thresholds: '80 80'
    
        - name: Publish Code Coverage to Build Step Summary
          run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
    
        - name: Upload Coverage Report Artifact
          uses: actions/upload-artifact@v3
          with: 
            name: CoverageReport
            path: build/artifacts/testResults/codeCoverage