name: PR-Build

on:
  pull_request:
    branches: [ "main", "develop" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET 7.x
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.x

    - name: Build and Run Tests
      run: ./build.sh --target=PullRequestBuild
      shell: bash